chia_location: C:\Users\b\AppData\Local\chia-blockchain\app-1.1.7\resources\app.asar.unpacked\daemon\chia.exe

manager:
  check_interval: 60
  log_level: INFO

log:
  folder_path: C:\Users\b\.chia\mainnet\plotter

view:
  check_interval: 5
  datetime_format: "%Y-%m-%d %H:%M:%S"
  include_seconds_for_phase: false
  include_drive_info: true
  include_cpu: true
  include_ram: true
  include_plot_stats: true

notifications:
  # DISCORD
  notify_discord: true
  discord_webhook_url: https://discord.com/api/webhooks/851736549199446046/ptZlfYwNmChtJ9LECfg7ZRQ-NiE_qt7BU4iLuLD23x3K31f6qOWwdkweSf4o8otMgzTF
  # chia-notifications1: https://discord.com/api/webhooks/840625619956006964/XDAb7z2rOSCoUMUHI14rI_medt5sWLAtshD5PjNjRO_dEJW8Ns-dgectwqXK5RTLTnOe
  # chia-notifications2: https://discord.com/api/webhooks/851736549199446046/ptZlfYwNmChtJ9LECfg7ZRQ-NiE_qt7BU4iLuLD23x3K31f6qOWwdkweSf4o8otMgzTF

  # PLAY AUDIO SOUND
  notify_sound: false
  song: audio.mp3
  # PUSHOVER PUSH SERVICE
  notify_pushover: false
  pushover_user_key: xx
  pushover_api_key: xx
  # TWILIO
  notify_twilio: false
  twilio_account_sid: xxxxx
  twilio_auth_token: xxxxx
  twilio_from_phone: +1234657890
  twilio_to_phone: +1234657890

instrumentation:
  # This setting is here in case you wanted to enable instrumentation using Prometheus.
  prometheus_enabled: false
  prometheus_port: 9090

progress:
  phase1_line_end: 801
  phase2_line_end: 834
  phase3_line_end: 2474
  phase4_line_end: 2620
  phase1_weight: 33.4
  phase2_weight: 20.43
  phase3_weight: 42.29
  phase4_weight: 3.88

global:
  max_concurrent: 5
  max_for_phase_1: 2
  minimum_minutes_between_jobs: 5

jobs:
- name: bPlotDouble
  farmer_public_key: 89acc1edcdb1502946dbfd3fb146933d41c20ed235e3ce51ccdd3aece02048c23813d20e40a70fca21f268b968fa0ae0
  pool_public_key: b56714782950a549c67ed0aafa7c25923ac707f25c5b5ec958df2ffdc501d1d64d5c52261a304462dfd1a2e58473429f

  temporary_directory: E:\
  temporary2_directory: F:\
  destination_directory: 
    - Y:\
    - Z:\
  max_plots: 72
  
  size: 32
  bitfield: true
  threads: 12
  buckets: 128
  memory_buffer: 3400
  max_concurrent: 4
  max_concurrent_with_start_early: 5
  stagger_minutes: 85
  max_for_phase_1: 2

  concurrency_start_early_phase: 2
  concurrency_start_early_phase_delay: 10
  temporary2_destination_sync: false

