chia_location: /home/bharvest/chia-blockchain/venv/bin/chia

manager:
  check_interval: 60
  log_level: INFO

log:
  folder_path: /home/bharvest/chia-logs-swar

view:
  check_interval: 5
  datetime_format: "%Y-%m-%d %H:%M:%S"
  include_seconds_for_phase: false
  include_drive_info: true
  include_cpu: true
  include_ram: true
  include_plot_stats: true


notifications:
  # DISCORD
  notify_discord: true
  discord_webhook_url: https://discord.com/api/webhooks/840625619956006964/XDAb7z2rOSCoUMUHI14rI_medt5sWLAtshD5PjNjRO_dEJW8Ns-dgectwqXK5RTLTnOe 
  # PLAY AUDIO SOUND
  notify_sound: false
  song: audio.mp3
  # PUSHOVER PUSH SERVICE
  notify_pushover: false
  pushover_user_key: xx
  pushover_api_key: xx
  # TWILIO
  notify_twilio: false
  twilio_account_sid: xxxxx
  twilio_auth_token: xxxxx
  twilio_from_phone: +1234657890
  twilio_to_phone: +1234657890

progress:
  phase1_line_end: 801
  phase2_line_end: 834
  phase3_line_end: 2474
  phase4_line_end: 2620
  phase1_weight: 33.4
  phase2_weight: 20.43
  phase3_weight: 42.29
  phase4_weight: 3.88

global:
  max_concurrent: 1

jobs:
- name: bLinuxTest
  temporary_directory: '/media/bharvest/Chia Temp1'
  destination_directory: /media/bharvest/Chia5
  max_plots: 1
  
  size: 32
  bitfield: true
  threads: 8
  buckets: 128
  memory_buffer: 3400
  max_concurrent: 1
  max_concurrent_with_start_early: 1
  stagger_minutes: 120
  max_for_phase_1: 1
  concurrency_start_early_phase: 1
  concurrency_start_early_phase_delay: 10
  temporary2_destination_sync: false

